# Generated by Django 5.1.6 on 2025-12-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='subjects/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('pass_score', models.PositiveIntegerField(default=0, verbose_name='نمره')),
                ('xp_reward', models.PositiveIntegerField(default=0, verbose_name='xp')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'مرحله\u200cها',
                'ordering': ['order'],
            },
        ),
    ]
