# Generated by Django 5.1.6 on 2026-02-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_lessonstage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.FileField(upload_to='subjects/', verbose_name='عکس'),
        ),
    ]
