# Generated by Django 5.1.6 on 2025-12-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='ارائه شده')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='درس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گواهی',
                'verbose_name_plural': 'گواهی\u200cها',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='نمره')),
                ('is_passed', models.BooleanField(default=False, verbose_name='پذیرفته')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='تکمیل شده')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='subjects.lessonstage', verbose_name='مرحله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت',
                'verbose_name_plural': 'پیشرفت\u200cها',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='تمام xp')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='لول')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='ستریک')),
                ('last_activity_date', models.DateTimeField(auto_now_add=True, verbose_name='آخرین فعالیت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمارها',
                'ordering': ['-last_activity_date'],
            },
        ),
    ]
