# Generated by Django 5.1.6 on 2025-12-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='سؤال')),
                ('type', models.CharField(choices=[('multiple-choice', 'چند گزینه\u200cای'), ('true-or-false', 'صحیح یا غلط')], max_length=50, verbose_name='نوع')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب سؤال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='subjects.lessonstage', verbose_name='مرحله')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'سؤال\u200cها',
                'ordering': ['order'],
                'unique_together': {('stage', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='متن')),
                ('is_correct', models.BooleanField(default=False, verbose_name='صحیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='سؤال')),
            ],
            options={
                'verbose_name': 'انتخاب',
                'verbose_name_plural': 'انتخاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
